name: Thank Contributors

on:
  push:
    branches:
      - main
      - develop
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  thank:
    runs-on: ubuntu-latest

    steps:
      - name: Thank contributor
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const contributor = context.payload.pusher.name;
            const commitSha = context.sha.substring(0, 7);
            const commitMessage = context.payload.head_commit.message.split('\n')[0];

            const commentBody = `🎉 Thank you @${contributor} for contributing!\n\n` +
                                `Commit: ${commitSha}\n` +
                                `Message: "${commitMessage}"\n\n` +
                                `Your contributions make this project better! 🚀`;

            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody
            });